99959:OTP attempt exceeded and OTP expired changes
sunbird-cb/sunbird-lms-service pull request #31
Opened 2023-09-12 12:31 UTC by ravisaurav-tarento

2023-09-12 12:32 UTC, ravisaurav-tarento commented
Hi @karthik-tarento Please review the Pull Request

2023-09-12 14:24 UTC, karthik-tarento requested changes

2023-09-12 14:24 UTC, karthik-tarento commented on service/src/main/java/org/sunbird/actor/otp/OTPActor.java
> +    if (remainingCount >= 0) {
It should be > 0 
equal to should not come

2023-09-12 14:24 UTC, karthik-tarento commented on core/platform-common/src/main/java/org/sunbird/exception/ResponseMessage.java
> +    String ERROR_OTP_ATTEMPT_EXCEEDED = "Attempt Exceeded For the OTP, Please Try Again.";;
Number of attempts exceeded for OTP verification. Please try again.

2023-09-12 14:24 UTC, karthik-tarento commented on core/platform-common/src/main/java/org/sunbird/exception/ResponseMessage.java
> +    String ERROR_OTP_EXPIRED = "OTP Expired, Please Try Again.";
OTP expired, Please try again.

2023-09-13 07:14 UTC, ravisaurav-tarento commented on service/src/main/java/org/sunbird/actor/otp/OTPActor.java
> +    if (remainingCount >= 0) {
I have removed equality check for this variable.

2023-09-13 07:15 UTC, ravisaurav-tarento commented on core/platform-common/src/main/java/org/sunbird/exception/ResponseMessage.java
> +    String ERROR_OTP_EXPIRED = "OTP Expired, Please Try Again.";
I have updated both the error messages.

2023-09-13 11:37 UTC, merged